[package]
name = "zero2prod"
version = "0.1.0"
authors = ["José Augusto S. de Moura <josemoura212@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.5.1"
tokio = {version = "1.37.0",features = ["macros", "rt-multi-thread"]}
