application:
  port: 8000
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity-catiau"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-token-postmark"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"
